name: zmp
channels:
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - asttokens==3.0.0
      - cmeel==0.57.3
      - cmeel-assimp==5.4.3.1
      - cmeel-boost==1.87.0.1
      - cmeel-console-bridge==1.0.2.3
      - cmeel-octomap==1.10.0
      - cmeel-qhull==8.0.2.1
      - cmeel-tinyxml2==10.0.0
      - cmeel-urdfdom==4.0.1
      - cmeel-zlib==1.3.1
      - coal==3.0.1
      - contourpy==1.3.2
      - control==0.10.2
      - cycler==0.12.1
      - decorator==5.2.1
      - drake==1.43.0
      - eigenpy==3.10.3
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fonttools==4.60.1
      - ipython==8.37.0
      - jedi==0.19.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.5
      - matplotlib-inline==0.2.1
      - meshcat==0.3.2
      - mujoco==3.3.0
      - numpy==2.2.6
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - pin==3.7.0
      - plyfile==1.1.2
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybullet==3.2.7
      - pydot==4.0.1
      - pygments==2.19.2
      - pyngrok==7.4.1
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pyroboplan==1.3.0
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - scipy==1.15.3
      - six==1.17.0
      - stack-data==0.6.3
      - tomli==2.3.0
      - toppra==0.6.3
      - tornado==6.5.2
      - traitlets==5.14.3
      - u-msgpack-python==2.8.0
      - wcwidth==0.2.14
      - zipp==3.23.0
prefix: /home/wzn/miniconda3/envs/fuck
